// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodePilot.Infrastructure.Persistence;

#nullable disable

namespace NodePilot.Infrastructure.Migrations
{
    [DbContext(typeof(NodePilotDbContext))]
    [Migration("20260601004003_ExtendSystemMetricsModel")]
    partial class ExtendSystemMetricsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("NodePilot.Application.Monitoring.SystemMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTime>("CollectedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("collected_at_utc");

                    b.Property<bool>("CpuEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("cpu_enabled");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("REAL")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<bool>("RamEnabled")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ram_enabled");

                    b.Property<double?>("RamUsagePercent")
                        .HasColumnType("REAL")
                        .HasColumnName("ram_usage_percent");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.Property<int>("SuccessfulReads")
                        .HasColumnType("INTEGER")
                        .HasColumnName("successful_reads");

                    b.Property<int>("TotalReads")
                        .HasColumnType("INTEGER")
                        .HasColumnName("total_reads");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc")
                        .HasDatabaseName("ix_system_metrics_collected_at_utc");

                    b.HasIndex("Status", "CollectedAtUtc")
                        .HasDatabaseName("ix_system_metrics_status_collected_at_utc");

                    b.ToTable("system_metrics", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_metrics_cpu_usage_percent_range", "cpu_usage_percent IS NULL OR (cpu_usage_percent >= 0 AND cpu_usage_percent <= 100)");

                            t.HasCheckConstraint("ck_system_metrics_partial_success_shape", "(status != 1 OR (successful_reads > 0 AND successful_reads < total_reads AND failure_reason IS NOT NULL))");

                            t.HasCheckConstraint("ck_system_metrics_ram_usage_percent_range", "ram_usage_percent IS NULL OR (ram_usage_percent >= 0 AND ram_usage_percent <= 100)");

                            t.HasCheckConstraint("ck_system_metrics_read_failed_shape", "(status != 2 OR (successful_reads = 0 AND failure_reason IS NOT NULL))");

                            t.HasCheckConstraint("ck_system_metrics_reads_valid", "total_reads >= 0 AND successful_reads >= 0 AND successful_reads <= total_reads");

                            t.HasCheckConstraint("ck_system_metrics_success_shape", "(status != 0 OR (successful_reads = total_reads AND failure_reason IS NULL))");

                            t.HasCheckConstraint("ck_system_metrics_total_reads_matches_enabled_metrics", "total_reads = (CASE WHEN cpu_enabled THEN 1 ELSE 0 END) + (CASE WHEN ram_enabled THEN 1 ELSE 0 END)");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
