// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodePilot.Infrastructure.Persistence;

#nullable disable

namespace NodePilot.Infrastructure.Migrations
{
    [DbContext(typeof(NodePilotDbContext))]
    partial class NodePilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("SystemMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<double>("CpuUsagePercent")
                        .HasColumnType("REAL");

                    b.Property<double>("RamUsagePercent")
                        .HasColumnType("REAL");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc")
                        .HasDatabaseName("ix_system_metrics_collected_at_utc");

                    b.ToTable("system_builders", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_metrics_cpu_usage_percent_range", "cpu_usage_percent >= 0 AND cpu_usage_percent <= 100");

                            t.HasCheckConstraint("ck_system_metrics_ram_usage_percent_range", "ram_usage_percent >= 0 AND ram_usage_percent <= 100");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
