// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NodePilot.Infrastructure.Persistence;

#nullable disable

namespace NodePilot.Infrastructure.Migrations
{
    [DbContext(typeof(NodePilotDbContext))]
    partial class NodePilotDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.6");

            modelBuilder.Entity("NodePilot.Application.SystemStatus.SystemMetric", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CollectedAtUtc")
                        .HasColumnType("TEXT")
                        .HasColumnName("collected_at_utc");

                    b.Property<double?>("CpuUsagePercent")
                        .HasColumnType("REAL")
                        .HasColumnName("cpu_usage_percent");

                    b.Property<string>("FailureReason")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT")
                        .HasColumnName("failure_reason");

                    b.Property<double?>("RamUsagePercent")
                        .HasColumnType("REAL")
                        .HasColumnName("ram_usage_percent");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("CollectedAtUtc")
                        .HasDatabaseName("ix_system_metrics_collected_at_utc");

                    b.HasIndex("Status", "CollectedAtUtc")
                        .HasDatabaseName("ix_system_metrics_status_collected_at_utc");

                    b.ToTable("system_metrics", null, t =>
                        {
                            t.HasCheckConstraint("ck_system_metrics_cpu_usage_percent_range", "cpu_usage_percent IS NULL OR (cpu_usage_percent >= 0 AND cpu_usage_percent <= 100)");

                            t.HasCheckConstraint("ck_system_metrics_ram_usage_percent_range", "ram_usage_percent IS NULL OR (ram_usage_percent >= 0 AND ram_usage_percent <= 100)");

                            t.HasCheckConstraint("ck_system_metrics_read_failed_shape", "(status != 1 OR (cpu_usage_percent IS NULL AND ram_usage_percent IS NULL AND failure_reason IS NOT NULL))");

                            t.HasCheckConstraint("ck_system_metrics_success_shape", "(status != 0 OR (cpu_usage_percent IS NOT NULL AND ram_usage_percent IS NOT NULL AND failure_reason IS NULL))");
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
